### ISSUE TITLE
how to close a mqtt that it's no longer needed?

### ISSUE THREAD

**Issue by ramarro123** [sclausen/angular2-mqtt#10]
in a webapp with auth user input, i will need to create a mqtt after a user login and destroy it when user logout.

any way to disconnect (apart reloading the page)?

**Comment by sclausen** [comment]
Currently this isn't implemented, but that's a not very far fetched usecase, so I'll have a look at that…

**Comment by sclausen** [comment]
[1.7.1](/sclausen/angular2-mqtt/releases/tag/1.7.1) now offers you to subscribe on a few events.
Feel free to open another issue, if you've got any issues or questions.
