### ISSUE TITLE
how to catch wrong username/password?

### ISSUE THREAD

**Issue by ramarro123** [sclausen/angular2-mqtt#11]
hi again :)

sorry for a dumb question, i would like to know how to catch event like wrong user/password during mqtt negotiation, to display some sort of popup or alert.

Also, at the moment, the library try to connect forever even if user/pwd are wrong?

tnx

**Comment by sclausen** [comment]
Yes, you're right, currently it tries to reconnect, if you configured `autoReconnect`.
I think the service should emit proper events for this and some other cases so you can subscribe on them.

**Comment by sclausen** [comment]
The new version [1.7.1](/sclausen/angular2-mqtt/releases/tag/1.7.1) implements this feature. I hope, this suits your needs.
Feel free to open another issue, if you've got any issues or questions.

**Comment by ramarro123** [comment]
tnx, i'll try in the next few days!

**Comment by ramarro123** [comment]
@sclausen  sorry to ping on a closed ticket, but do u have a sample for that?
i can't really understand how it work

**Comment by ramarro123** [comment]
i have try with

```
    this.mqtt.onReconnect.subscribe(() => {
      console.log("onReconnect");
    });

    this.mqtt.onClose.subscribe(() => {
      console.log("onClose");
    });


    this.mqtt.onConnect.subscribe(() => {
      console.log("onConnect");
    });

    this.mqtt.onError.subscribe(() => {
      console.log("onError");
    });

```

and if i connect with wrong user/password
i see only onClose & onReconnect event, not the onConnect nor the onError

**Comment by sclausen** [comment]
I don't know which broker you use, so I provoked an error with bad credentials in [hummingbird](https://github.com/lpeterse/haskell-hummingbird) and got this `onError` event:
```
Error: Connection refused: Not authorized
    at u._handleConnack (ngx-mqtt.min.js:7)
    at u._handlePacket (ngx-mqtt.min.js:7)
    at t (ngx-mqtt.min.js:7)
    at a.n._write (ngx-mqtt.min.js:7)
    at l (ngx-mqtt.min.js:7)
    at f (ngx-mqtt.min.js:7)
    at a.write (ngx-mqtt.min.js:7)
    at p.a (ngx-mqtt.min.js:7)
    at p.r.emit (ngx-mqtt.min.js:7)
    at s (ngx-mqtt.min.js:7)
```

I also tried mosquitto and you're totally right, with this broker, just the connection closes without an error!
I tried mosquitto with nodejs too. I used the plain library MQTT.js, which ngx-translate is based upon, and if the credentials are wrong, I get an error…So I researched a little and found, that this is a known bug in mosquittos websockets [eclipse/mosquitto/issues/18](https://github.com/eclipse/mosquitto/issues/18)
