### ISSUE TITLE
Version update

### ISSUE THREAD

**Issue by marekburiak** [sclausen/angular2-mqtt#2]
Hi,
any chance you could update the packages (like rxjs to 5.0.1 and maybe others) as it's giving me errors when I try to use it in a project generated with the current angular-cli (version 1.0.0-beta.24).
Like for example:

```
msgs: Observable<MqttMessage> = null;
this.msgs = this.mqttService.observe("#");
```

errors out with:
Type `Observable<MqttMessage>` is not assignable to type` Observable<MqttMessage>`. Two different types with this name exist, but they are unrelated.

I guess it comes from a different version of rxjs.

**Comment by sclausen** [comment]
Thank you for this isuse, I will fix it today.

**Comment by sclausen** [comment]
This issue should be resolved with the new version. If you encounter any problems, please let me know.

**Comment by marekburiak** [comment]
Thanks.
Btw. I am getting the following error (and I was getting it in the previous version as well).

ERROR in Error encountered resolving symbol values statically. Calling function 'MqttModule', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppModule in d:/My Documents/Projects/Web/HA5/src/app/app.module.ts, resolving symbol AppModule in d:/My Documents/Projects/Web/HA5/src/app/app.module.ts

Connection to the broker seems to work despite the error. Haven't tried to pub/sub yet.

app.module.ts:
```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule, Component } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';
import { Observable } from 'rxjs/Observable';
import {
  MqttMessage,
  MqttModule,
  MqttService
} from 'angular2-mqtt';

import { AppComponent } from './app.component';

 
export function mqttServiceFactory() {
  return new MqttService({
    hostname: 'nuc',
    port: 9001,
    path: ''
  });
}  

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    FormsModule,
    HttpModule,
    MqttModule.forRoot({
      provide: MqttService,
      useFactory: mqttServiceFactory
    }),
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

**Comment by sclausen** [comment]
Ah yes, I recognize this. I think this is an AoT related error. I will dig into this on monday at work.
