### ISSUE TITLE
AoT compilation error

### ISSUE THREAD

**Issue by sclausen** [sclausen/angular2-mqtt#3]
@marekburiak wrote:

Thanks.
Btw. I am getting the following error (and I was getting it in the previous version as well).

ERROR in Error encountered resolving symbol values statically. Calling function 'MqttModule', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppModule in d:/My Documents/Projects/Web/HA5/src/app/app.module.ts, resolving symbol AppModule in d:/My Documents/Projects/Web/HA5/src/app/app.module.ts

Connection to the broker seems to work despite the error. Haven't tried to pub/sub yet.

app.module.ts:
```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule, Component } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';
import { Observable } from 'rxjs/Observable';
import {
  MqttMessage,
  MqttModule,
  MqttService
} from 'angular2-mqtt';

import { AppComponent } from './app.component';

 
export function mqttServiceFactory() {
  return new MqttService({
    hostname: 'nuc',
    port: 9001,
    path: ''
  });
}  

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    FormsModule,
    HttpModule,
    MqttModule.forRoot({
      provide: MqttService,
      useFactory: mqttServiceFactory
    }),
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

I have uploaded the whole project to [HA5.zip](http://www.megafileupload.com/cnjT/HA5.ZIP)

**Comment by sclausen** [comment]
@marekburiak: Okay, total strange behavior, can't get why this won't work.
It works well with angular-cli@1.0.0-beta.20-1

**Comment by marekburiak** [comment]
Ok, I appreciate you taking a look at it. Hopefully it will get fixed with some newer version of angular or typescript or whatever is causing it. Thanks for a great lib.

**Comment by Herbert-Hotz** [comment]
Hi,
I see exactly the same error using 'angular-cli@1.0.0-beta.24':

ERROR in Error encountered resolving symbol values statically. Calling function 'MqttModule', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppModule in D:/NodejsProjects/ng2-mqtt/src/app/app.module.ts, resolving symbol AppModule in D:/NodejsProjects/ng2-mqtt/src/app/app.module.ts

BTW, I'm using Windows 10 64 bit version.

I would appreciate a fix or workaround asap - want to use angular2-mqtt for a project.

Thanks!

**Comment by Herbert-Hotz** [comment]
Awesome support - thanks a lot!
