### ISSUE TITLE
How does one publish a message?

### ISSUE THREAD

**Issue by marekburiak** [sclausen/angular2-mqtt#4]
Am I missing something, or does this lib only support subscriptions? Would you consider exposing publish function from MQTT lib?

**Comment by sclausen** [comment]
Yes, sorry I missed this one. Now included in brand new 1.3.0 ;)

**Comment by marekburiak** [comment]
ok, here's my component:
`import { Component, OnInit } from '@angular/core';
import {
  MqttMessage,
  MqttModule,
  MqttService
} from 'angular2-mqtt';

@Component({
  selector: 'app-publish',
  templateUrl: './publish.component.html',
  styleUrls: ['./publish.component.css']
})
export class PublishComponent implements OnInit {

  constructor(public mqttService: MqttService) { }

  public click() {
    console.log("publishing");
    this.mqttService.publish("test", "message");
  }

  ngOnInit() { }
}`

Clicking the button does not publish anything. If I change 
`private client: MQTT.client`

to public and then in the component call 
`this.mqttService.client.publish("test", "message");`

it does publish just fine. Am I missing something when calling mqttService.publish?

**Comment by sclausen** [comment]
Since publish returns an observable, you have to subscribe to it.
Depending on the qos, this may be curcial, because with qos 1 or 2, the publication may fail for several reasons.

**Comment by marekburiak** [comment]
I use qos 0, seems reliable enough in my local network and it should be most performant as well. So I do not really care about what the publish returns. Also creating an observable on each publish seems like an overhead in my case (although not sure how much of an overhead it is). I am publishing for example on a slider move (to control light brightness) so I'd like to publish as fast as possible (from an older hardware).
The publish function from mqtt has the callback as an optional argument. Would you consider making it optional/no observable in your wrapper as well?

**Comment by sclausen** [comment]
Do you think a unsafePublish would suit your needs? I'll dig into that.

**Comment by sclausen** [comment]
Here it is: `1.4.0`
I hope, it's what you need.

**Comment by marekburiak** [comment]
Publish working great and the compilation error is gone too, Thanks!
