### ISSUE TITLE
Ability to pass in more options

### ISSUE THREAD

**Issue by marekburiak** [sclausen/angular2-mqtt#5]
hey, me again :)
If you get a chance, could you please expose more options from mqtt lib? I am mainly interested in these:

keepalive
clientId
clean
reconnectPeriod
connectTimeout
username
password
will

For example reconnectPeriod and connectTimeout are hardcoded to 10s and I'd like to be able to change it. I am running a client on a mobile phone and mqtt disconnects when mobile goes to sleep. When I wake it up it takes up to 10s to reconnect. So I'd like to be able to change it to 1s.

**Comment by sclausen** [comment]
Yes, that's a good point. Unfortunately I'm busy today, so I'll fix this this evening, or tomorrow.

**Comment by marekburiak** [comment]
Thank you!
