### ISSUE TITLE
Auth

### ISSUE THREAD

**Issue by Cst2989** [sclausen/angular2-mqtt#7]
Hello,

How can I add username and password to the MQTT_SERVICE_OPTIONS ?

I tried to with normal username and password, but I get ERR_CONNECTION_RESET

Or change the connection to tsl ?

When I try to change the protocol to mqtt it still uses ws:

stream.js:43 WebSocket connection to 'ws://m20.cloudmqtt.com:39338/' failed: Error during WebSocket handshake: net::ERR_CONNECTION_RESET

**Comment by sclausen** [comment]
You can pass all options available in [ClientOptions from mqtt.js](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/mqtt/index.d.ts) including username and password and additional options like `protocol` (either ws or wss) defined [here](https://github.com/sclausen/angular2-mqtt/blob/master/src/mqtt.model.ts)
